#!/usr/bin/env groovy

@Library('jenkins-pipelayer')_

pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    stages {
        stage('Generate Jobs') {
            steps {
                script {
                checkout scm
                // this will generate jobs from folder jobs to jenkins folder pipelines
                generateJobs {
                    gitConfigJenkinsBranch = 'master'
                    gitRemoteUrl = 'git-uri'
                    path = 'jobs/**/*.groovy'
                    destination = 'pipelines'
                }
                }
            }
        }
    }
}
