#!/usr/bin/env groovy

@Library('jenkins-pipelayer')_

pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '100'))
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    stages {
        stage('Generate Jobs') {
            steps {
                checkout scm
                // this will generate jobs from folder jobs to jenkins folder pipelines
                generateJobs 
            }
        }
    }
}
